management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: logs/library.log
  health:
    defaults:
      enabled: true
mongock:
  change-logs-scan-package:
    - ru.otus.library.changelogs
logging:
  file:
    name: logs/library.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
  level:
    root: INFO
spring:
  data:
    mongodb:
      database: library
      port: 27017
      uri: mongodb://localhost
